<!DOCTYPE html>
<html lang="EN" xml:lang="en">
  <head>
    <title></title>
    <style>
      ul {
        list-style-type: none;
        margin: 0;
        padding: 0;
        overflow: hidden;
        background-color: #333;
      }

      li {
        float: left;
      }

      li a {
        display: block;
        color: white;
        text-align: center;
        padding: 14px 16px;
        text-decoration: none;
      }

      li a:hover {
        background-color: #111;
      }
    </style>
  </head>
  <body>
    <ul>
      <li><a class="active" href="task1.php">Task1</a></li>
      <li><a href="task2.php">Task2</a></li>
      <li><a href="task3.php">Task3</a></li>
      <li><a href="task4.php">Task4</a></li>
    </ul>
  </body>
</html>
